# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1361360ddfddf96d4e2688a9cb054b6e9be2a377a8c438b6f0956faa1cef5610f11fa70f5b4d01b4f28d97b9157274a6b79fcca39825cd69a14847fd9c768330

test:
  secret_key_base: 24da7be7a6ddbd657a958b33e948b10bb036ed571f663f861b80a125c02003c587eed1092dcc9c7692409e7c78d68483bda137ab48f05d1c7c17c4dad4a615a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
